#!/bin/bash

if [ ! -z "$1" ]; then
	unset BINUCHARDET_PHONY
	unset BINUCHARDET_PHONY_CLEAN
	if [ "${HAVE_BIN_UCHARDET}" = "1" ]; then
		export BINUCHARDET_NAME="uchardet"
		export BINUCHARDET_BIN="${BINUCHARDET_NAME}${BINSUFFIX}"
		export BINUCHARDET="$1"
		export BINUCHARDET_PHONY="BINUCHARDET"
		export BINUCHARDET_PHONY_CLEAN="BINUCHARDET_CLEAN"
		export BINUCHARDET_CFLAGS=
		export BINUCHARDET_LDFLAGS=
		echo "BINUCHARDET=${BINUCHARDET}"
	fi
fi

