# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset LIBMATPLOT_PHONY
	unset LIBMATPLOT_PHONY_CLEAN
	if [ "${HAVE_LIBMATPLOT}" = "1" ]; then
		export LIBMATPLOT_NAME="v1.2.1"
		export LIBMATPLOT_SUBNAME="sh"
		export LIBMATPLOT="$1"
		export LIBMATPLOT_OBJS_DIR=${RUNTIME_OBJS}${LIBMATPLOT/${ROOT}/""}
		export LIBMATPLOT_RESULT="${LIBMATPLOT_OBJS_DIR}/${LIBMATPLOT_NAME}.${LIBMATPLOT_SUBNAME}_RESULT"
		export LIBMATPLOT_RESULT_CLEAN="${LIBMATPLOT_RESULT}_clean"
		export LIBMATPLOT_PHONY="LIBMATPLOT"
		export LIBMATPLOT_PHONY_CLEAN="LIBMATPLOT_CLEAN"
		export LIBMATPLOT_CFLAGS=
		export LIBMATPLOT_LDFLAGS="-lmatplot -lpng -ljpeg -ltiff"
	fi
fi

