# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset SWAGGERCODEGENCLI_PHONY
	unset SWAGGERCODEGENCLI_PHONY_CLEAN
	if [ "${HAVE_SWAGGERCODEGENCLI}" = "1" ]; then
		export SWAGGERCODEGENCLI_NAME="swagger-codegen-cli-3.0.24"
		export SWAGGERCODEGENCLI_SUBNAME=""
		export SWAGGERCODEGENCLI_CONFIG_H="was_configure"
		export SWAGGERCODEGENCLI="$1"
		export SWAGGERCODEGENCLI_OBJS_DIR=${RUNTIME_OBJS}${SWAGGERCODEGENCLI/${ROOT}/""}
		export SWAGGERCODEGENCLI_BIN="${SWAGGERCODEGENCLI_OBJS_DIR}/${SWAGGERCODEGENCLI_NAME}/${SWAGGERCODEGENCLI_NAME}.jar"
		export SWAGGERCODEGENCLI_BIN_CLEAN="${SWAGGERCODEGENCLI_BIN}_clean"
		export SWAGGERCODEGENCLI_PHONY="SWAGGERCODEGENCLI"
		export SWAGGERCODEGENCLI_PHONY_CLEAN="SWAGGERCODEGENCLI_CLEAN"
		export SWAGGERCODEGENCLI_CFLAGS=
		export SWAGGERCODEGENCLI_LDFLAGS=""
		echo "SWAGGERCODEGENCLI=${SWAGGERCODEGENCLI}"
		
    export SWAGGERCODEGENCLI_BIN="java -jar ${SWAGGERCODEGENCLI_BIN}"
		alias SWAGGERCODEGENCLI_BIN="${SWAGGERCODEGENCLI_BIN}"

		export SWAGGERCODEGENCLI_GEN_GOCLIENT="${SWAGGERCODEGENCLI_BIN} generate -l go --additional-properties packageName=swagger"
		alias SWAGGERCODEGENCLI_GEN_GOCLIENT="${SWAGGERCODEGENCLI_GEN_GOSERVER}"
		
		export SWAGGERCODEGENCLI_GEN_GOSERVER="${SWAGGERCODEGENCLI_BIN} generate -l go-server --additional-properties packageName=swagger"
		alias SWAGGERCODEGENCLI_GEN_GOSERVER="${SWAGGERCODEGENCLI_GEN_GOSERVER}"
		
		export SWAGGERCODEGENCLI_GEN_HTML2="${SWAGGERCODEGENCLI_BIN} generate -l html2 "
		alias SWAGGERCODEGENCLI_GEN_HTML2="${SWAGGERCODEGENCLI_GEN_HTML2}"
	fi
fi
