# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GHCFILESYSTEM_PHONY
	unset GHCFILESYSTEM_PHONY_CLEAN
	if [ "${HAVE_GHCFILESYSTEM}" = "1" ]; then
		export GHCFILESYSTEM_NAME="ghcfilesystem_v1.4.0"
		export GHCFILESYSTEM_SUBNAME="sh"
		export GHCFILESYSTEM="$1"
		export GHCFILESYSTEM_OBJS_DIR=${RUNTIME_OBJS}${GHCFILESYSTEM/${ROOT}/""}
		export GHCFILESYSTEM_RESULT="${GHCFILESYSTEM_OBJS_DIR}/${GHCFILESYSTEM_NAME}.${GHCFILESYSTEM_SUBNAME}_RESULT"
		export GHCFILESYSTEM_RESULT_CLEAN="${GHCFILESYSTEM_RESULT}_clean"
		export GHCFILESYSTEM_PHONY="GHCFILESYSTEM"
		export GHCFILESYSTEM_PHONY_CLEAN="GHCFILESYSTEM_CLEAN"
		export GHCFILESYSTEM_CFLAGS=-I${GHCFILESYSTEM_OBJS_DIR}/filesystem/include
		export GHCFILESYSTEM_LDFLAGS=""
		echo "GHCFILESYSTEM=${GHCFILESYSTEM}"
	fi
fi

