# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset X8664W64MINGWDLLS_PHONY
	unset X8664W64MINGWDLLS_PHONY_CLEAN
	if [ "${HAVE_X8664W64MINGWDLLS}" = "1" ]; then
		export X8664W64MINGWDLLS_NAME="6.3.0"
		export X8664W64MINGWDLLS_SUBNAME="sh"
		export X8664W64MINGWDLLS="$1"
		export X8664W64MINGWDLLS_OBJS_DIR=${RUNTIME_OBJS}${X8664W64MINGWDLLS/${ROOT}/""}
		export X8664W64MINGWDLLS_RESULT="${X8664W64MINGWDLLS_OBJS_DIR}/${X8664W64MINGWDLLS_NAME}.${X8664W64MINGWDLLS_SUBNAME}_RESULT"
		export X8664W64MINGWDLLS_RESULT_CLEAN="${X8664W64MINGWDLLS_RESULT}_clean"
		export X8664W64MINGWDLLS_PHONY="X8664W64MINGWDLLS"
		export X8664W64MINGWDLLS_PHONY_CLEAN="X8664W64MINGWDLLS_CLEAN"
		export X8664W64MINGWDLLS_CFLAGS=
		export X8664W64MINGWDLLS_LDFLAGS=""
		echo "X8664W64MINGWDLLS=${X8664W64MINGWDLLS}"
	fi
fi

