# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GOSWAGGERCLI_PHONY
	unset GOSWAGGERCLI_PHONY_CLEAN
	if [ "${HAVE_GOSWAGGERCLI}" = "1" ]; then
		export GOSWAGGERCLI_NAME="goswaggercli_0.26.1"
		export GOSWAGGERCLI_SUBNAME=""
		export GOSWAGGERCLI_CONFIG_H="was_configure"
		export GOSWAGGERCLI="$1"
		export GOSWAGGERCLI_OBJS_DIR=${RUNTIME_OBJS}${GOSWAGGERCLI/${ROOT}/""}
		export GOSWAGGERCLI_BIN="${GOSWAGGERCLI_OBJS_DIR}/${GOSWAGGERCLI_NAME}/${GOSWAGGERCLI_NAME}"
		export GOSWAGGERCLI_BIN_CLEAN="${GOSWAGGERCLI_BIN}_clean"
		export GOSWAGGERCLI_PHONY="GOSWAGGERCLI"
		export GOSWAGGERCLI_PHONY_CLEAN="GOSWAGGERCLI_CLEAN"
		export GOSWAGGERCLI_CFLAGS=
		export GOSWAGGERCLI_LDFLAGS=""
		echo "GOSWAGGERCLI=${GOSWAGGERCLI}"
	fi
fi
