export HAVE_LIB_SYS=1
export HAVE_LIB_KLIB=1
export HAVE_LIB_LODEPNG=1
export HAVE_LIB_UCHARDET=1
export HAVE_BIN_UCHARDET=1

export HAVE_LIB_ICONV=1
export HAVE_LIB_OPENSSL=1
export HAVE_LIB_EVENT=1
export HAVE_LIB_JANSSON=1

export HAVE_LIB_X264=1
export HAVE_LIB_FDKAAC=1
export HAVE_LIB_FFMPEG=1

