# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset LIBCPPZMQ_PHONY
	unset LIBCPPZMQ_PHONY_CLEAN
	if [ "${HAVE_LIB_CPPZMQ}" = "1" ]; then
		export LIBCPPZMQ_NAME="v4.10.0"
		export LIBCPPZMQ_SUBNAME="sh"
		export LIBCPPZMQ="$1"
		export LIBCPPZMQ_OBJS_DIR=${RUNTIME_OBJS}${LIBCPPZMQ/${ROOT}/""}
		export LIBCPPZMQ_HOST_BIN_DIR=${LIBCPPZMQ_OBJS_DIR}/host_bin
		export LIBCPPZMQ_RESULT="${LIBCPPZMQ_OBJS_DIR}/${LIBCPPZMQ_NAME}.${LIBCPPZMQ_SUBNAME}_RESULT"
		export LIBCPPZMQ_RESULT_CLEAN="${LIBCPPZMQ_RESULT}_clean"
		export LIBCPPZMQ_PHONY="LIBCPPZMQ"
		export LIBCPPZMQ_PHONY_CLEAN="LIBCPPZMQ_CLEAN"
		export LIBCPPZMQ_CFLAGS=
		echo "LIBCPPZMQ=${LIBCPPZMQ}"
	fi
fi