# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset PROTOCGENGO_PHONY
	unset PROTOCGENGO_PHONY_CLEAN
	if [ "${HAVE_PROTOCGENGO}" = "1" ]; then
		export PROTOCGENGO_NAME="protoc-gen-go"
		export PROTOCGENGO_SUBNAME=""
		export PROTOCGENGO_CONFIG_H="was_configure"
		export PROTOCGENGO="$1"
		export PROTOCGENGO_OBJS_DIR=${RUNTIME_OBJS}${PROTOCGENGO/${ROOT}/""}
		export PROTOCGENGO_BIN="${GOBIN}/protoc-gen-go${HOST_BINSUFFIX}"
		export PROTOCGENGO_BIN_CLEAN="${PROTOCGENGO_BIN}_clean"
		export PROTOCGENGO_PHONY="PROTOCGENGO"
		export PROTOCGENGO_PHONY_CLEAN="PROTOCGENGO_CLEAN"
		export PROTOCGENGO_CFLAGS=
		export PROTOCGENGO_LDFLAGS=""
		echo "PROTOCGENGO=${PROTOCGENGO}"
	fi
fi

