# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

SHELL := /bin/bash


################ Build external/libx264/libx264-2.1.8.tar.gz ##########
include $(MK_RESET)
#TARGET_PKG_URL=https://ftp.videolan.org/pub/pub/videolan/x264/snapshots
TARGET_PKG_URL=https://mirror.yandex.ru/mirrors/ftp.videolan.org/x264/snapshots
TARGET_PKG_FILE=${LIBX264_NAME}.${LIBX264_SUBNAME}
TARGET_PKG_DIR=${LIBX264_NAME}
TARGET_PKG_SUBNAME=${LIBX264_SUBNAME}
TARGET_PKG_CONFIG_H=${LIBX264_NAME}/${LIBX264_CONFIG_LOG}
TARGET_PKG_CONFIG=./configure 
ifneq (, $(findstring mingw, $(PLATFORM)))
TARGET_PKG_CONFIG+=--prefix=$(RUNTIME) --disable-cli --enable-shared --enable-win32thread --host=$(MINGW_W64) --cross-prefix=$(CROSS_COMPILE1) --chroma-format=420 --disable-avs --extra-ldflags='-Wl,-static -Wl,--output-def=libx264-142.def'
else ifneq (, $(findstring linux, $(PLATFORM)))
TARGET_PKG_CONFIG+=--prefix=$(RUNTIME) --disable-cli --enable-shared --chroma-format=420 --disable-avs
else ifneq (, $(findstring mac, $(PLATFORM)))
TARGET_PKG_CONFIG+=--prefix=$(RUNTIME) --disable-cli --enable-shared --chroma-format=420 --disable-avs
else ifneq (, $(findstring arm-linux-gnueabihf, $(PLATFORM)))
MY_EX_CFLAGS='-mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard'
MY_EX_LDFLAGS=$(MY_EX_CFLAGS)
TARGET_PKG_CONFIG+=--prefix=$(RUNTIME) --disable-cli --enable-shared --host=$(MINGW_W64) --cross-prefix=$(CROSS_COMPILE1) --chroma-format=420 --disable-avs --extra-cflags=$(MY_EX_CFLAGS) --extra-ldflags=$(MY_EX_LDFLAGS)
endif
TARGET_PKG_LIB=${RUNTIME_LIB}/${LIBX264_LIB}
TARGET_PKG_LIB_CLEAN=${TARGET_PKG_LIB}_clean
include $(MK_PKG)

