name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux_x86-64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install build tools 
      run:
        sudo apt-get -y install cmake unzip zip nasm yasm libsdl2-dev libsdl2-mixer-dev autoconf bison gawk libtool libtool-bin 
    - name: configure
      run: PF=linux source source.sh
    - name: make
      run: PF=linux source source.sh && make

##################################################################
#  There is a build issue with Ubuntu 22.04's g++-mingw-w64-x86-64.
##################################################################
#  build_linux_mingw-w64:
#    runs-on: ubuntu-22.04
#    steps:
#    - name: Checkout repository and submodules
#      uses: actions/checkout@v3
#      with:
#        submodules: recursive
#    - name: Install build tools 
#      run:
#        sudo apt-get -y install cmake unzip zip nasm yasm libsdl2-dev libsdl2-mixer-dev autoconf bison gawk libtool libtool-bin g++-mingw-w64-x86-64
#    - name: configure
#      run: PF=mingw.linux source source.sh
#    - name: make
#      run: PF=mingw.linux source source.sh && make
####################################################################
